require:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# Common configuration.
AllCops:
  TargetRubyVersion: 2.7.0
  # Include common Ruby source files.
  Include:
  - 'app/**/*.rb'
  - '**/*.rake'
  - '**/config.ru'
  - '**/Gemfile'
  - '**/Rakefile'
  Exclude:
  - 'app/views/**/*'
  - 'app/mailers/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'bin/**/*'
  - 'public/**/*'
  - 'spec/**/*'
  DisplayCopNames: false
  DisplayStyleGuide: true
  UseCache: false
  DefaultFormatter: progress

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

# Checks formatting of special comments
Style/CommentAnnotation:
  Keywords:
  - TODO
  - NOTE
  - FIXME
  - OPTIMIZE
  - HACK
  - REVIEW

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  MinBodyLength: 3

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/SymbolArray:
  EnforcedStyle: percent

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/PredicateName:
  ForbiddenPrefixes:
  - is_
  - has_
  - have_

Style/SingleLineBlockParams:
  Methods:
  - reduce:
    - acc
    - elem
  - inject:
    - acc
    - elem

Style/StringLiterals:
  Exclude:
  - 'db/schema.rb'

##################### Metrics ##################################

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 32

Metrics/BlockLength:
  Exclude:
  - 'lib/tasks/**.rake'
  - "spec/**/*.rb"

Metrics/ClassLength:
  Max: 130

Metrics/ModuleLength:
  Max: 120
  Exclude:
  - "spec/**/*.rb"

Metrics/CyclomaticComplexity:
  Max: 8

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 8

##################### Rails ##################################

Rails/DynamicFindBy:
  Whitelist:
  - find_by_sql
  - find_by_encrypted_id

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf
